Repository OpenMined/KotlinSyft, pull requests merged in 2020-07, with the labels that each got.

#213 Tests for SyftTensor
  .gitignore
  buildSrc/src/main/java/Dependencies.kt
  syftlib/build.gradle
  syftlib/src/main/java/org/openmined/syft/proto/State.kt
  syftlib/src/main/java/org/openmined/syft/proto/SyftModel.kt
  syftlib/src/main/java/org/openmined/syft/proto/SyftTensor.kt
  syftlib/src/test/java/org/openmined/syft/proto/SyftTensorTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/execution/PlanTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/proto/SyftModelTest.kt
Labels: Type: Refactor :hammer:, Type: Testing :test_tube:

#217 Report diff
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/MnistViewModel.kt
  syftlib/src/main/assets/torchscripts/diff_script.pt
  syftlib/src/main/java/org/openmined/syft/Syft.kt
  syftlib/src/main/java/org/openmined/syft/datasource/JobLocalDataSource.kt
  syftlib/src/main/java/org/openmined/syft/domain/JobRepository.kt
  syftlib/src/main/java/org/openmined/syft/execution/Plan.kt
  syftlib/src/main/java/org/openmined/syft/execution/SyftJob.kt
  syftlib/src/main/java/org/openmined/syft/networking/datamodels/syft/ReportDataModels.kt
  syftlib/src/main/java/org/openmined/syft/proto/State.kt
  syftlib/src/main/java/org/openmined/syft/proto/SyftModel.kt
  syftlib/src/main/java/org/openmined/syft/proto/SyftState.kt
  syftlib/src/main/java/org/openmined/syft/proto/SyftTensor.kt
  syftlib/src/test/java/org/openmined/syft/datasource/JobLocalDataSourceTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/datasource/JobLocalDataSourceTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/datasource/JobRemoteDataSourceTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/domain/JobRepositoryTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/execution/SyftJobTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/proto/SyftModelTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/proto/SyftTensorTest.kt
Labels: Priority: 1 - Immediate :fire:, Severity: 2 - High :cold_sweat:, Status: Completed :heavy_check_mark:, Type: New Feature :heavy_plus_sign:

#220 Background demo
  buildSrc/src/main/java/Dependencies.kt
  demo-app/build.gradle
  demo-app/src/main/AndroidManifest.xml
  demo-app/src/main/java/org/openmined/syft/demo/federated/datasource/LocalMNISTDataDataSource.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/domain/TrainingTask.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/logging/MnistLogger.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/service/FederatedWorker.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/service/WorkerRepository.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/ContentState.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/MnistViewModel.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/MnistViewModelFactory.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/main/MnistActivity.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/main/MnistActivityViewModel.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/main/MnistViewModelFactory.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/work/WorkInfoActivity.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/work/WorkInfoViewModel.kt
  demo-app/src/main/java/org/openmined/syft/demo/federated/ui/work/WorkInfoViewModelFactory.kt
  demo-app/src/main/java/org/openmined/syft/demo/login/LoginActivity.kt
  demo-app/src/main/res/layout/activity_mnist.xml
  demo-app/src/main/res/layout/activity_work_info.xml
  demo-app/src/main/res/values/colors.xml
  demo-app/src/main/res/values/strings.xml
  syftlib/build.gradle
  syftlib/src/main/java/org/openmined/syft/domain/SyftConfiguration.kt
  syftlib/src/main/java/org/openmined/syft/monitor/DeviceMonitor.kt
  syftlib/src/test/java/org/openmined/syft/integration/AuthenticationTest.kt
  syftlib/src/test/java/org/openmined/syft/integration/DeviceMonitorTest.kt
  syftlib/src/test/java/org/openmined/syft/integration/DownloadablesTest.kt
  syftlib/src/test/java/org/openmined/syft/integration/MultipleSyftJobsTest.kt
  syftlib/src/test/java/org/openmined/syft/integration/SpeedIntegrationTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/SyftTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/domain/SyftConfigurationTest.kt
  syftlib/src/test/java/org/openmined/syft/unit/monitor/DeviceMonitorTest.kt
Labels: Priority: 1 - Immediate :fire:, Severity: 2 - High :cold_sweat:, Status: In Progress :star2:, Type: Epic :call_me_hand:
